name: Trigger auto deployment for cognitube-transcoding-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cognitube-transcoding-service-AutoDeployTrigger-c02e5f8f-e6e5-404e-9647-3edba73c0075.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.COGNITUBETRANSCODINGSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COGNITUBETRANSCODINGSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COGNITUBETRANSCODINGSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: cogregdev.azurecr.io
          registryUsername: ${{ secrets.COGNITUBETRANSCODINGSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COGNITUBETRANSCODINGSERVICE_REGISTRY_PASSWORD }}
          containerAppName: cognitube-transcoding-service
          resourceGroup: Cognitube
          imageToBuild: cogregdev.azurecr.io/cognitube-transcoding-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


